services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - apache
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  apache:
    container_name: apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/certs/yourdomain.crt:/etc/ssl/certs/yourdomain.crt
      - ./apache/certs/yourdomain.key:/etc/ssl/private/yourdomain.key

  ollama:
    container_name: ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports: 
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  app-network:
    driver: bridge
